In [22]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 

In [23]:
df = pd.read_csv("ManualLRDS.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'ManualLRDS.csv'

In [ ]:
df.head()

In [4]:
#Training we calculate beta 
x = df['x']
y = df['y']
xVec = X=(np.column_stack((np.ones(np.size(x)),x)))


In [5]:
xVec.shape


(4, 2)

In [6]:
X_T = np.transpose(xVec)
X_T.shape

(2, 4)

In [7]:
X_T

array([[1. , 1. , 1. , 1. ],
       [0.5, 1.2, 2.9, 3.7]])

In [8]:
xVec

array([[1. , 0.5],
       [1. , 1.2],
       [1. , 2.9],
       [1. , 3.7]])

In [9]:
e1 = np.dot(X_T,xVec)
e1 = np.linalg.inv(e1)

In [10]:
e2 = np.dot(X_T,y)

In [11]:
Beta = np.dot(e1,e2)

In [12]:
Beta

array([-0.00529121,  1.02664636])

In [13]:
Beta.shape

(2,)

In [14]:
x_predict = np.array([[1,1.7]])

In [15]:
x_predict.shape


(1, 2)

In [16]:
y_predict = np.dot(x_predict,Beta)

In [17]:
y_predict

array([1.74000761])

In [18]:
collectY_Hats= []
for i in range(len(y)):
    collectY_Hats.append(np.dot(xVec[i],Beta))

In [19]:
collectY_Hats

[0.508031975637609, 1.2266844309097829, 2.9719832508564905, 3.7933003425961185]

In [20]:
each_Y_Minus_Yhat = []
sum_Squares = 0
for i in range(len(y)):
    each_Y_Minus_Yhat.append((y[i]-collectY_Hats[i])**2)
    sum_Squares = sum_Squares+each_Y_Minus_Yhat[i]

In [21]:
sum_Squares

0.2853368861819558